### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by MartinIngesen** [tghack/tg17hack#1]
Heisann!

Kanskje det kunne vært en idé å lage et dokument med scoreboardet slik det endte opp til slutt?

**Comment by maritiren** [comment]
Ja, det var en god idé^_^ Jeg fikser i løpet av dagen elns!

**Comment by roypur** [comment]
Her ligger scoreboardet slik det endte opp. https://tghack.github.io/tg17hack/

**Comment by pewz** [comment]
Lukker denne.
